cart/urls.py
from django.urls import path
from .views import cart_add, cart_remove, cart_detail

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", cart_add, name="cart_add"),
    path("remove/<int:product_id>/", cart_remove, name="cart_remove"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("",include("core.urls")),
    path("tienda/", include("products.urls")),
    path("carrito/", include("cart.urls")),
    path("orden/", include("orders.urls")),
    path("dashboard/", include("dashboard.urls")),
    



   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .import views


app_name = "orders"

urlpatterns = [
    path("crear/", views.order_create, name="order_create"),
    path("pagar/<int:order_id>/", views.create_mp_preference, name="mp_pagar"),
    path("<int:order_id>/", views.order_detail, name="order_detail"),
    
    path("pago/exito/<int:order_id>/", views.pago_exito, name="pago_exito"),
    path("pagos/error/", views.pago_error, name="pago_error"),
    path("pagos/pendiente/", views.pago_pendiente, name="pago_pendiente"),
    # mercadopago
    path("pagos/webhook/", views.mercadopago_webhook, name="mp_webhook"),

    path("mis-compras/", views.mis_compras, name="mis_compras"),
    path("factura/<int:order_id>/", views.factura_pdf, name="factura_pdf"),



    





    

]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    quantity = int(request.POST.get("quantity", 1))
    cart.add(product=product, quantity=quantity)

    return redirect("cart_detail")


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart_detail")


def cart_detail(request):
    cart = Cart(request)
    return render(request, "cart/cart_detail.html", {
        "cart": cart
    })

cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% block title %}Carrito{% endblock %}

{% block content %}
<div class="container py-5">
    <h2>Carrito de compras</h2>

    {% if cart %}
        <table class="table">
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    <tr>
                        <td>{{ item.product.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>$ {{ item.price }}</td>
                        <td>$ {{ item.total_price }}</td>
                        <td>
                            <a href="{% url 'cart_remove' item.product.id %}"
                               class="btn btn-sm btn-danger">
                               Eliminar
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <h4 class="text-end">
            Total: $ {{ cart.get_total_price }}
        </h4>

        <div class="text-end">
            <a href="{% url 'orders:order_create' %}" class="btn btn-success">
                Continuar compra
            </a>

        </div>
    {% else %}
        <p>Tu carrito está vacío</p>
    {% endif %}
</div>
{% endblock %}