cart/urls.py
from django.urls import path
from .views import cart_add, cart_remove, cart_detail

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", cart_add, name="cart_add"),
    path("remove/<int:product_id>/", cart_remove, name="cart_remove"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("",include("core.urls")),
    path("tienda/", include("products.urls")),
    path("carrito/", include("cart.urls")),
    path("orden/", include("orders.urls")),
    path("dashboard/", include("dashboard.urls")),
    



   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .import views


app_name = "orders"

urlpatterns = [
    path("crear/", views.order_create, name="order_create"),
    path("pagar/<int:order_id>/", views.create_mp_preference, name="mp_pagar"),
    path("<int:order_id>/", views.order_detail, name="order_detail"),
    
    path("pago/exito/<int:order_id>/", views.pago_exito, name="pago_exito"),
    path("pagos/error/", views.pago_error, name="pago_error"),
    path("pagos/pendiente/", views.pago_pendiente, name="pago_pendiente"),
    # mercadopago
    path("pagos/webhook/", views.mercadopago_webhook, name="mp_webhook"),

    path("mis-compras/", views.mis_compras, name="mis_compras"),
    path("factura/<int:order_id>/", views.factura_pdf, name="factura_pdf"),



    





    

]

templates/base/footer.html
<footer class="bg-dark text-light py-4 mt-5">
    <div class="container text-center">
        <p class="mb-1">&copy; {{ year|default:2026 }} MiEcommerce</p>
        <small>Todos los derechos reservados</small>
    </div>
</footer>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand fw-bold" href="/">MiEcommerce</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="#">Tienda</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Ofertas</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Contacto</a></li>
                <li class="nav-item">
                <a class="btn btn-outline-light ms-2" href="{% url 'cart_detail' %}">
                    Carrito ({{ cart|length }})
                </a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard_home' %}">
                        Dashboard
                    </a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'orders:mis_compras' %}">
                        Mis compras
                    </a>
                </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>